/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.canvasbeeapp;

import javax.swing.JOptionPane;
import mapbd.EvasaoInter;
import objetoacesso.EvasaoInterDAO;

/**
 *
 * @author lucim
 */
public class InterdisciplinarE extends javax.swing.JFrame {
    static int ident;
    static String aluno;
    /**
     * Creates new form InterdisciplinarE
     */
    public InterdisciplinarE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSliderQ1 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblQ1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSliderQ2 = new javax.swing.JSlider();
        lblQ2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSliderQ3 = new javax.swing.JSlider();
        lblQ3 = new javax.swing.JLabel();
        jSliderQ4 = new javax.swing.JSlider();
        lblQ4 = new javax.swing.JLabel();
        bntEnviar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rbQ5op1 = new javax.swing.JRadioButton();
        rbQ5op2 = new javax.swing.JRadioButton();
        rbQ5op3 = new javax.swing.JRadioButton();
        rbQ5op4 = new javax.swing.JRadioButton();
        rbQ5op5 = new javax.swing.JRadioButton();
        rbQ5op6 = new javax.swing.JRadioButton();
        lblAluno = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucim\\OneDrive\\Documentos\\NetBeansProjects\\CanvasBeeApp\\src\\main\\java\\com\\mycompany\\canvasbeeapp\\abelha-64px.png")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jornada Interativa de Aprendizagem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Estratégias e Interdisciplinar");

        jSliderQ1.setMajorTickSpacing(1);
        jSliderQ1.setMaximum(10);
        jSliderQ1.setPaintLabels(true);
        jSliderQ1.setPaintTicks(true);
        jSliderQ1.setSnapToTicks(true);
        jSliderQ1.setToolTipText("");
        jSliderQ1.setValue(5);
        jSliderQ1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderQ1StateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Em escala de 0 a 10 (0 = nada e 10 = muito), respondas as questões:");

        jLabel5.setText("1- Você se sente engajado(a) nas atividades do Programa Aprendiz?");

        lblQ1.setText("5");

        jLabel10.setText("2- Quanto aos desafio pessoais como: transporte e alimentação, isso dificulta sua partici-");

        jLabel11.setText("pação no programa?");

        jSliderQ2.setMajorTickSpacing(1);
        jSliderQ2.setMaximum(10);
        jSliderQ2.setPaintLabels(true);
        jSliderQ2.setPaintTicks(true);
        jSliderQ2.setSnapToTicks(true);
        jSliderQ2.setValue(5);
        jSliderQ2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderQ2StateChanged(evt);
            }
        });

        lblQ2.setText("5");

        jLabel13.setText("3- As atividades em grupo e a colaboração com os colegas te deixa confortável?");

        jSliderQ3.setMajorTickSpacing(1);
        jSliderQ3.setMaximum(10);
        jSliderQ3.setPaintLabels(true);
        jSliderQ3.setPaintTicks(true);
        jSliderQ3.setSnapToTicks(true);
        jSliderQ3.setValue(5);
        jSliderQ3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderQ3StateChanged(evt);
            }
        });

        lblQ3.setText("5");

        jSliderQ4.setMajorTickSpacing(1);
        jSliderQ4.setMaximum(10);
        jSliderQ4.setPaintLabels(true);
        jSliderQ4.setPaintTicks(true);
        jSliderQ4.setSnapToTicks(true);
        jSliderQ4.setValue(5);
        jSliderQ4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderQ4StateChanged(evt);
            }
        });

        lblQ4.setText("5");

        bntEnviar.setBackground(new java.awt.Color(0, 0, 153));
        bntEnviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntEnviar.setForeground(new java.awt.Color(255, 255, 255));
        bntEnviar.setText("Enviar");
        bntEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEnviarActionPerformed(evt);
            }
        });

        jLabel9.setText("4- Quanto apoio você sente da sua família para continuar no programa?");

        jLabel12.setText("5- Como você avalia seu equilíbrio entre estudos, trabalho e vida pessoal?");

        buttonGroup1.add(rbQ5op1);
        rbQ5op1.setText("Não preciso de equilíbrio nos estudos, nem na vida pessoal, nem no trabalho.");

        buttonGroup1.add(rbQ5op2);
        rbQ5op2.setText("Equilíbro apenas meu trabalho.");

        buttonGroup1.add(rbQ5op3);
        rbQ5op3.setText("Equilíbro apenas minha vida pessoal.");

        buttonGroup1.add(rbQ5op4);
        rbQ5op4.setText("Equilíbro meu trabalho e minha vida pessoal.");

        buttonGroup1.add(rbQ5op5);
        rbQ5op5.setText("Equilíbro meus estudos e minha vida pessoal.");

        buttonGroup1.add(rbQ5op6);
        rbQ5op6.setText("Equilíbro meus estudos, minha vida pessoal e o trabalho muito bem.");

        lblAluno.setText("Aluno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSliderQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(lblQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSliderQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(lblQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rbQ5op1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jSliderQ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53)
                                    .addComponent(lblQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(rbQ5op2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbQ5op3, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbQ5op4, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbQ5op5, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbQ5op6, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSliderQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(lblQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bntEnviar)
                        .addGap(98, 98, 98))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSliderQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQ2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQ3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSliderQ3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderQ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(lblQ4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbQ5op1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbQ5op2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbQ5op3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbQ5op4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbQ5op5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbQ5op6)
                .addGap(18, 18, 18)
                .addComponent(bntEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderQ1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderQ1StateChanged
        int valorq1 = jSliderQ1.getValue();
        lblQ1.setText(String.valueOf(valorq1));
        


    }//GEN-LAST:event_jSliderQ1StateChanged

    private void bntEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEnviarActionPerformed
        //int engajamento, desafios, colaboracao, familia, equilibrio;
        int engajamento = Integer.parseInt(lblQ1.getText());
        int desafios = Integer.parseInt(lblQ2.getText());
        int colaboracao = Integer.parseInt(lblQ3.getText());
        int familia = Integer.parseInt(lblQ4.getText());
        int equilibrio = 0;
        int ident = Integer.parseInt(lblId.getText());
        if (rbQ5op1.isSelected()){
            equilibrio = 0;
        }
        if (rbQ5op2.isSelected()){
            equilibrio = 2;
        }
        if (rbQ5op3.isSelected()) {
            equilibrio = 4;
        }
        if (rbQ5op4.isSelected()) {
            equilibrio = 6;
        }
        if (rbQ5op5.isSelected()) {
            equilibrio = 8;
        }
        if (rbQ5op6.isSelected()) {
            equilibrio = 10;
        }
        int id_aluno = Integer.parseInt(lblId.getText());
        
        EvasaoInter evasao = new EvasaoInter();
        evasao.setEngajamento(engajamento);
        evasao.setDesafios(desafios);
        evasao.setColaboracao(colaboracao);
        evasao.setFamilia(familia);
        evasao.setEquilibrio(equilibrio);
        evasao.setId_aluno(id_aluno);
        
        
        EvasaoInterDAO evasaointerDAO = new EvasaoInterDAO();
        evasaointerDAO.inserir(evasao);
        
        JOptionPane.showMessageDialog(null,"Agradecemos sua participação! ");
        
        new Senac().setVisible(true);
        Senac.aluno = lblAluno.getText();
        Senac.lblAluno.setText(aluno);
        Senac.lblid.setText(String.valueOf(ident));
        Senac.lblid.setVisible(false);
           dispose();
    }//GEN-LAST:event_bntEnviarActionPerformed

    private void jSliderQ2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderQ2StateChanged
        int valorq2 = jSliderQ2.getValue();
        lblQ2.setText(String.valueOf(valorq2));
    }//GEN-LAST:event_jSliderQ2StateChanged

    private void jSliderQ3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderQ3StateChanged
        int valorq3 = jSliderQ3.getValue();
        lblQ3.setText(String.valueOf(valorq3));
    }//GEN-LAST:event_jSliderQ3StateChanged

    private void jSliderQ4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderQ4StateChanged
        int valorq4 = jSliderQ4.getValue();
        lblQ4.setText(String.valueOf(valorq4));
    }//GEN-LAST:event_jSliderQ4StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterdisciplinarE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterdisciplinarE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterdisciplinarE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterdisciplinarE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterdisciplinarE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEnviar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSliderQ1;
    private javax.swing.JSlider jSliderQ2;
    private javax.swing.JSlider jSliderQ3;
    private javax.swing.JSlider jSliderQ4;
    public static javax.swing.JLabel lblAluno;
    public static javax.swing.JLabel lblId;
    private javax.swing.JLabel lblQ1;
    private javax.swing.JLabel lblQ2;
    private javax.swing.JLabel lblQ3;
    private javax.swing.JLabel lblQ4;
    private javax.swing.JRadioButton rbQ5op1;
    private javax.swing.JRadioButton rbQ5op2;
    private javax.swing.JRadioButton rbQ5op3;
    private javax.swing.JRadioButton rbQ5op4;
    private javax.swing.JRadioButton rbQ5op5;
    private javax.swing.JRadioButton rbQ5op6;
    // End of variables declaration//GEN-END:variables
}
